run:
  skip-dirs:
    - swaggerspec
    - pkg/uiserver
  timeout: 2m

linters-settings:
  goimports:
    local-prefixes: github.com/pingcap/tidb-dashboard
  golint:
    min-confidence: 0

issues:
  include:
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0009
    - EXC0010

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - revive
    - gosec
    - unconvert
    - goimports
    - depguard
    - prealloc
    - exportloopref
    - whitespace
