run:
  skip-dirs:
    - swaggerspec
    - pkg/uiserver
  timeout: 2m

linters-settings:
  goimports:
    local-prefixes: github.com/pingcap/tidb-dashboard
  golint:
    min-confidence: 0

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - gosec
    - unconvert
    - goimports
    - depguard
    - prealloc
    - scopelint
    - whitespace
