name: Build

on: pull_request

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13.5"
      - name: Load go module cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Load golangci-lint cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/golangci-lint
          key: ${{ runner.os }}-golint
          restore-keys: |
            ${{ runner.os }}-golint
      - name: Lint and build
        run: |
          make dev
      - name: Check uncommitted lint changes
        run: |
          git diff --exit-code

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "ui/yarn.lock"
      - uses: actions/setup-go@v3
        with:
          go-version: "1.13.5"
      - name: Load go module cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install yarn packages
        run: |
          make yarn_dependencies
      - name: Check format
        run: |
          yarn prettier --check . || (echo "::error ::Please format your code by using 'yarn fmt'"; exit 1)
        working-directory: ui
      - name: Build UI
        run: |
          make ui
        env:
          NO_MINIMIZE: true
          CI: true
