name: Create Pull Request to PD

on:
  release:
    type: [released]

jobs:
  create_pr_to_pd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to pd
        uses: actions/checkout@master
        with:
          repository: tikv/pd
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          ACTOR=${{ github.actor }}
          git config user.name "$ACTOR"
          git config user.email "$ACTOR@pingcap.com"
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16.5"
      - name: Update dashboard
        run: |
          go get -d "github.com/pingcap/tidb-dashboard@$GITHUB_REF"
          go mod tidy
          make pd-server
          go mod tidy
          git add go.mod go.sum
          if git status | grep -q "Changes to be committed"
          then
            git commit --message "Update from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA, release version: $GITHUB_REF"
          else
            echo "No changes detected"
          fi
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          signoff: true
          branch: update-dashboard-$GITHUB_REF
          title: Update TiDB Dashboard to $GITHUB_REF
          body: Update TiDB dashboard from https://github.com/$GITHUB_REPOSITORY/commit/$GITHUB_SHA, release version is $GITHUB_REF
          push-to-fork: ${{ github.actor }}/pd
          reviewers: breeswish
