name: Release Check

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check release version
        run: git diff --name-only --exit-code release -- ./release-version || (echo "Please update the release version file" && false)
